### PR TITLE
Added Directory badges

### PR DESCRIPTION
**Pull request by binhbbbb**
Hi, 

Your component is listed on Vaadin Directory. We think it would be cool to showcase these badges. For more information on how to generate these badges, head to this [guide](https://vaadin.com/blog/vaadin-directory-now-welcomes-custom-github-badges).

Binh

### CODE REVIEW

**Comment by nick-woodward** [comment]
Thanks for the contribution, I'll check out this PR later tonight since I'll have to look into why the build is failing.

**Comment by binhbbbb** [comment]
Sure thing!

**Comment by nick-woodward** [comment]
@binhbbbb Sorry its taken me so long to get to this. I've been busy working on other projects.

Feel free to open pull requests for the other repositories.

**Comment by binhbbbb** [comment]
Hi @nick-woodward, I'm glad that this is not gone into dust. I will be making those other PRs today, feel free to check it at your own convenient time.

**Pull request merged**
